# docker run --name dns-server -p 53:53/udp -p 5380:5380 -d technitium/dns-server

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      no_proxy: "${NO_PROXY}"
    networks:
      whale-network:
        ipv4_address: 192.168.85.2
    volumes:
      - /srv/nginx/conf.d:/etc/nginx/conf.d
      #- /srv/nginx/certs:/etc/nginx/certs
      #- /srv/nginx/www:/www

  dns-server:
    image: technitium/dns-server
    container_name: dns-server
    restart: always
    ports:
      - 53:53/udp
    networks:
      whale-network:
        ipv4_address: 192.168.85.3
    volumes:
      - /etc/dns:/etc/dns

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    networks:
      whale-network:
        ipv4_address: 192.168.85.4
    volumes:
      - /var/lib/prometheus/data:/prometheus/data
      - /srv/prometheus/targets:/etc/prometheus/targets
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana:latest-ubuntu
    container_name: grafana
    restart: always
    user: "${UID}:${GID}"
    environment:
      no_proxy: "${NO_PROXY}"
    networks:
      whale-network:
        ipv4_address: 192.168.85.5
    volumes:
      - /var/lib/grafana:/var/lib/grafana
  
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      whale-network:
        ipv4_address: 192.168.85.6
    volumes:
      - /var/lib/mysql:/var/lib/mysql
  
  sym:
    image: sym:latest
    container_name: sym
    restart: always
    networks:
      whale-network:
        ipv4_address: 192.168.85.7
    environment:
      NOTION_API_KEY: "${NOTION_API_KEY}" 
      NOTION_BUDGET_DB: "${NOTION_BUDGET_DB}" 
      NOTION_URL: "https://api.notion.com" 
      MYSQL_HOST: "${MYSQL_HOST}" 
      MYSQL_DB: "sym" 
      MYSQL_PORT: 3306 
      MYSQL_USER: "${MYSQL_USER}" 
      MYSQL_PASS: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - /var/lib/sym:/app
  
  rundeck:
    image: rundeck/rundeck:4.10.1
    container_name: rundeck
    restart: always
    ports:
      - 4440:4440
    environment:
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: "${MYSQL_USER}"
      RUNDECK_DATABASE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      RUNDECK_DATABASE_URL: jdbc:mysql://192.168.85.6/rundeck?autoReconnect=true&useSSL=false
      RUNDECK_SERVER_ADDRESS: 0.0.0.0
    networks:
      whale-network:
        ipv4_address: 192.168.85.8
    volumes:
      - /var/lib/rundeck:/home/rundeck


networks:
  whale-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.85.0/24
