services:
  bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    container_name: bind9
    ports:
      - 53:53
    volumes:
      - ./bind9/db.imbrisa.io:/etc/bind/db.imbrisa.io
      - ./bind9/named.conf.local:/etc/bind/named.conf.local
      - ./bind9/named.conf.option:/etc/bind/named.conf.option