global:
  scrape_interval:     30s
  evaluation_interval: 20s
  scrape_timeout:      30s

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 30s
    file_sd_configs:
    - files:
      - 'targets/node-exporter.json'