name: Deploy Whale
on: 
  workflow_dispatch:
  push:
jobs:  
  deploy:
    name: Deploy whale
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      
      - name: Stop containers
        run: sudo docker-compose down
      
      - name: Deploy containers
        run: sudo docker-compose up -d