name: Deploy Whale
on: 
  workflow_dispatch:
  push:
jobs:  
  deploy:
    name: Deploy whale
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Stop containers
        run: sudo docker-compose stop
      
      - name: Docker prune
        run: sudo docker system prune -f
      
      - name: Remove config files
        run: sudo rm -rf /srv/*

      - name: Sync files
        run: sudo rsync -av srv/* /srv/ --delete
      
      - name: Build SYM image
        run : |
          cd sym;
          sudo docker build --no-cache -t sym:latest .

      - name: Set env-file
        run: |
          echo "export MYSQL_HOST=${{vars.MYSQL_HOST}}" > .env
          echo "export MYSQL_USER=${{vars.MYSQL_USER}}" >> .env
          echo "export NOTION_BUDGET_DB=${{vars.NOTION_BUDGET_DB}}" >> .env
          echo "export NOTION_API_KEY=${{secrets.NOTION_API_KEY}}" >> .env
          echo "export MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}" >> .env

      - name: Deploy containers
        run: sudo docker-compose --env-file .env up -d
      
      - name: Change Rundeck password
        run: |
          sudo docker exec rundeck sed -i "s/admin:admin/admin:${{secrets.RUNDECK_ADMIN_PASSWORD}}/g" /home/rundeck/server/config/realm.properties
          sudo docker restart rundeck