name: Deploy Whale
on: 
  workflow_dispatch:
  push:
jobs:  
  deploy:
    name: Deploy whale
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Stop containers
        run: sudo docker-compose stop
      
      - name: Remove containers
        run: sudo docker ps -a --format '{{.Names}}' | xargs sudo docker rm -f

      
      - name: Sync files
        run: sudo rsync -av srv/* /srv/* --delete
      
      - name: Deploy containers
        run: sudo docker-compose up -d